- salsa20-family/Cargo.toml
I'm trying to phase out (and eventually yank) v0.8 for reasons it isn't impacted by: namely it included an implicit Drop impl in its custom derive support, and I'm trying to backtrack on that and ensure it's always explicit.
Before I yank it though, I want to ensure existing users are up-to-date.
> salsa20-family: Upgrade to zeroize v0.9

- chacha20/tests/chacha20.rs
- salsa20/tests/salsa20.rs
The `salsa20_offsets` and `chacha20_offsets` tests take an excessively long time to run (over a minute... I didn't bother to see how long they actually take because I got bored), slowing down both development and CI times.
Adding an `#[ignore]` attribute allows them to still be run with:
$ cargo test -- --ignored
That way they can still be run if desired, but don't slow down development or CI unnecessarily.
> Add #[ignore] attribute to tests that take excessively long to run

- .travis.yml
- chacha20/src/lib.rs
- salsa20-core/src/lib.rs
- salsa20-core/src/salsa_family_state.rs
- salsa20/src/lib.rs
This uses a CI config more like the one at:
https://github.com/RustCrypt/signatures
It runs all tests with the `--release` flag to ensure that crates aren't broken by release-dependent functionality after being tested in debug mode (we can add back debug mode testing if it's helpful, but it doesn't look like we have anything presently gated on debug builds). I now see @newpavlov also requested it on #20.
It also tests on a `no_std` platform (thumbv7) which @newpavlov requested in #18.
Finally, it tests with `--all-features`. This should uncover some lingering breakages (it won't in this commit, but it appears some of the conditional compilation is incorrectly gated and I intend to fix it in a follow-up commit).
> .travis.yml: Test no_std platform, WASM, all feature combos, --release

- chacha20/Cargo.toml
- chacha20/src/lib.rs
- chacha20/tests/chacha20.rs
This change factors almost all of the functionality into the `ChaChaState` type, and removes the generic `N: ArrayLength<u8>` parameter from the original `ChaCha20` type, instead splitting it into two concrete types:
- `ChaCha20`: 96-bit nonce ("IETF" version)
- `ChaCha20Legacy`: 64-bit nonce under `legacy` Cargo feature
Splitting the types up this way is based on the observation that practically nothing uses `ChaCha20Legacy` version, and while we should still support it just in case something actually needs it for whatever reason, we should make it easy to select the version that practically
everything uses.
Without this change there are some really nasty type inference problems with `NewStreamCipher` where an explicit type annotation is needed even if there is a default generic …
> chacha20: Refactor into `ChaCha20` and `ChaCha20Legacy`

- .travis.yml
...with the `--release` flag so they should be comparatively quick versus the excessively long time they take without it.
I think it's a nice tradeoff to have these run in CI with `--release`, but avoid switching local development to excessively optimize in debug mode just for these particular tests.
> .travis.yml: Run --ignored tests

- salsa20-core/src/salsa_family_state.rs
As far as I can tell setting `word_idx` here accomplishes nothing as it's never read in the remainder of the function.
It was originally added in this commit, and as far as I can tell has always been a spurious assignment:
https://github.com/RustCrypto/stream-ciphers/commit/8572ba4#diff-e39e303466eee7b7ea454eb1e2faec3cR94
> salsa20-core: Address `word_idx`-related warning (closes #23)

- ctr/src/lib.rs
- salsa20-core/src/lib.rs
- salsa20/src/lib.rs
This fixes all of the clippy warnings which have trivial corrections.
There's one remaining one involving an unsafe pointer cast that's a little more thorny which I'd like to address separately.
> Fix trivial clippy warnings

- aes-ctr/src/lib.rs
- cfb-mode/src/lib.rs
- cfb8/src/lib.rs
- chacha20/src/lib.rs
- ctr/src/lib.rs
- ofb/src/lib.rs
- salsa20-core/src/lib.rs
- salsa20/src/lib.rs
...and add some basic documentation to crates with missing docs.
The Salsa20 Family crates could probably use a bit more documentation than this, but this is a start.
> Add #![deny(missing_docs)] to all crates

- aes-ctr/src/lib.rs
- cfb-mode/src/lib.rs
- cfb8/src/lib.rs
- chacha20/Cargo.toml
- chacha20/README.md
- chacha20/src/lib.rs
- ctr/src/lib.rs
- ofb/src/lib.rs
- salsa20-core/src/lib.rs
- salsa20/Cargo.toml
- salsa20/README.md
- salsa20/src/lib.rs
Improve rustdoc with examples and add a `README.md` to each crate
> Document chacha20 and salsa20 crates (closes #17)

- salsa20/Cargo.toml
- salsa20/src/lib.rs
For whatever reason this previously had a superfluous wrapper struct.
This refactor removes it.
Also, as `salsa20-core` already handles `zeroize`, like the corresponding change to the ChaCha20 crate this makes `zeroize` into a cargo feature which enables the corresponding feature on `salsa20-core`.
> salsa20: Refactor to eliminate needless wrapper structs

- chacha20/src/lib.rs
- salsa20-core/src/lib.rs
- salsa20/src/lib.rs
Previously they only impl'd `StreamCipher`
Additionally this fixes bugs in the previous `SyncStreamCipherSeek` impls on both ciphers by better encapsulating the block index and offset management in the `SalsaFamilyCipher` type. This allows the crate examples to use this impl in the documented examples, which is consistent with the other crates.
> impl SyncStreamCipher for Salsa20 and ChaCha20

- chacha20/src/cipher.rs
- chacha20/src/legacy.rs
- chacha20/src/lib.rs
- chacha20/src/xchacha20.rs
This commit primarily renames the previous `ChaChaState` type and factors it under `chacha20::cipher::Cipher`.
Additionally, it gets rid of a number of unnecessary things from the previous implementation:
- `ArrayLength` generic parameter
- `Deref`/`DerefMut` impls
- Macros to define them
Instead, `ChaCha20` and `ChaCha20Legacy` are now proper newtypes of `Cipher`, sharing a completely identical core cipher type, but also fully encapsulating it so it's no longer part of the public-facing API whatsoever.
To do that, each of `ChaCha20` and `ChaCha20Legacy` each impl `NewStreamCipher`, `SyncStreamCipher`, and `SyncStreamCipherSeek` directly. This is actually a good and important thing for `NewStreamCipher` in particular, since that is where the differences
between the two of them actually …
> chacha20: Extract and encapsulate Cipher type

- chacha20/Cargo.toml
- chacha20/src/lib.rs
- chacha20/src/xchacha20.rs
- salsa20-core/Cargo.toml
- salsa20/Cargo.toml
v0.2.0 release of the Salsa20 family cipher crates.
> chacha20/salsa20/salsa20-core v0.2.0

- salsa20-core/Cargo.toml
The `std` feature of `zeroize` was previously being activated.
This commit disables default features.
> salsa20-core: Don't implicitly depend on `zeroize/std`

- chacha20/src/lib.rs
These are important for computing ChaCha20 data volume limits
> chacha20: Add MAX_BLOCKS and BLOCK_SIZE constants

- salsa20-core/CHANGES.md
- salsa20-core/Cargo.toml
- Don't implicitly depend on `zeroize/std` (#46)
> salsa20-core v0.2.1

- salsa20/Cargo.toml
- salsa20/src/block.rs
- salsa20/src/lib.rs
- salsa20/src/xsalsa20.rs
- salsa20/tests/lib.rs
This PR adds XSalsa20 to the `salsa20` crate (addresses #53). The implementation is based on the XChaCha20 implementation in the `chacha20` crate. As in the `chacha20` crate, I have modified the `double_round` function in `salsa20/src/block.rs` so that it consists of multiple calls to a `quarter_round` function. This allows me to reuse `quarter_round` in the `hsalsa20` function.
I could not find test vectors for `hsalsa20`. However, I have I added test vectors for XSalsa20 to `salsa20/tests/lib.rs.` These test vectors were taken from the golang implementation of XSalsa20.
> Add XSalsa20

- chacha20/README.md
- salsa20/README.md
Most users need the AEAD versions of these algorithms, so include links in the README so they can find them.
> chacha20/salsa20: Link to AEAD ciphers in README.md

- chacha20/src/block/mod.rs
- chacha20/src/block/sse2.rs
- chacha20/src/cipher.rs
This implements an SSE2-based variant of ChaCha20.
I'd also be keen to help adding support for AVX2 and AVX512, but it looks like this may need larger changes (possibly in the `salsa20_core` crate) to allow for processing multiple blocks simultaneously?
On my machine (early 2016 MacBook, 1.1GHz M3), the SSE2 variant shows a good improvement over the scalar code, speeding up the benchmarks from 260MB/s to 327MB/s.
Aside from the core algorithm, here are some of the things I could use feedback on:
- Gating: I've only implemented compile-time feature detection for now, as that seemed easier. I could potentially add runtime detection as well, if you think that is useful? Additionally, I was considering to pull in `cfg-if` to simplify the detection logic, but wasn't sure if you wanted to have …
> chacha20: add SSE2 accelerated variant

- .travis.yml
- chacha20/Cargo.toml
- chacha20/benches/chacha20.rs
- test_aesni.sh
...with the `criterion-cycles-per-byte` plugin
This unfortunately means we can no-longer run tests for chacha20 against Rust 1.27.0, since it adds 2018 edition `dev-dependencies`. However, we can still confirm release builds against this version work.
As we're starting to reach a microoptimization stage, I think criterion will be extremely helpful in determining if our microoptimizations are actually improving performance.
Currently I'm getting between 5.1 - 5.8 cpb across the tests on a Kaby Lake i7. Curiously `-Ctarget-cpu=native` seems to negatively impact performance. I'm not seeing much difference between the software and SSE2 backends: +5% on the `chacha20/apply_keystream/1024` benchmark, negligible on the others (i.e. +1-2%)
> chacha20: Use criterion for benchmarking

- chacha20/CHANGES.md
- chacha20/Cargo.toml
- chacha20/src/block/mod.rs
- chacha20/src/cipher.rs
- chacha20/src/lib.rs
- SSE2 accelerated implementation ([#61])
[#61]: https://github.com/RustCrypto/stream-ciphers/pull/61
> chacha20 v0.2.2

- hc-256/Cargo.toml
- salsa20-core/Cargo.toml
Release notes: https://github.com/iqlusioninc/crates/pull/279
> hc-256/salsa20-core: Upgrade to zeroize v1.0

- salsa20-core/CHANGES.md
- salsa20-core/Cargo.toml
- Upgrade to `zeroize` 1.0 final release ([#66])
[#66]: https://github.com/RustCrypto/stream-ciphers/pull/66
> salsa20-core v0.2.3

- chacha20/src/cipher.rs
If the counter overflows a 32-bit value, the keystream will be reused, with an impact of equal severity to nonce reuse (i.e. XOR of the ciphertexts reveals the XOR of plaintexts)
This commit adds a stopgap solution which panics in the event this happens.
A better fix would involve a breaking change to the `salsa20-core` crate to make the `SalsaFamilyCipher::block` method fallible. However, in the interests of releasing a minimal fix to this issue, this commit opts to panic instead.
cc @srijs
> [SECURITY] chacha20: ensure block counter < MAX_BLOCKS (fixes #64)

- chacha20/Cargo.toml
- chacha20/src/cipher.rs
- chacha20/src/lib.rs
- chacha20/src/rng.rs
This is a quick-and-dirty implementation for testing (could do with seek implementation and better doc at least).
> Add rand_core::RngCore implementation to chacha20

- ctr/src/lib.rs
The deprecation warnings on `mem::uninitialized` are breaking CI.
`mem::uninitialized` and `mem::zeroed` have  equivalent performance characteristics for the case where memory is always written to first, so this change should otherwise have no impact on performance.
> ctr: Replace deprecated `mem::uninitialized` with `mem::zeroed`

- chacha20/src/block/mod.rs
The original implementation was unnecessarily complicated. This removes a bunch of needlessly complex code.
This has no measurable effect on performance.
> chacha20: simplify implementation

- .travis.yml
- chacha20/Cargo.toml
- chacha20/benches/chacha20.rs
- chacha20/src/block.rs
- chacha20/src/block/soft.rs
- chacha20/src/block/sse2.rs
- chacha20/src/cipher.rs
- chacha20/src/lib.rs
- chacha20/src/rng.rs
- chacha20/src/xchacha20.rs
- chacha20/tests/lib.rs
- Upgrades the `chacha20` crate to Rust 2018 edition
- Refactors the SSE2 backend to sit side-by-side w\ pure software one
> chacha20: make 2018 edition crate; minor refactoring

- chacha20/src/block/soft.rs
- ctr/src/lib.rs
- hc-256/src/lib.rs
- salsa20/src/block.rs
- Fixes all existing clippy warnings
- Applies same refactoring from #75 to the `salsa20` crate
> clippy fixups; salsa20 refactor

- .travis.yml
- chacha20/Cargo.toml
- chacha20/README.md
- chacha20/src/cipher.rs
- chacha20/src/xchacha20.rs
Uses the `core` endianess conversions instead
> chacha20: remove `byteorder` dependency

- .travis.yml
- chacha20/README.md
- chacha20/src/block.rs
- chacha20/src/block/avx2.rs
Adds an AVX2 backend based on the `goll_gueron` ChaCha20 implementation from SUPERCOP:
https://github.com/jedisct1/supercop/tree/master/crypto_stream/chacha20/goll_gueron
> chacha20: AVX2 backend

- chacha20/src/lib.rs
- chacha20/src/rng.rs
See the writeup I've already done for the `rand_chacha` crate for the rationale of including these by default:
https://github.com/rust-random/rand/issues/932
tl;dr: the "Too Much Crypto" paper goes into why ChaCha20 is overkill, ChaCha12 is probably what should've been standardized per the eSTREAM analysis of Salsa20 (but wasn't for cargo cult reasons), and ChaCha8 is still (probably) safe:
https://eprint.iacr.org/2019/1492
> chacha20: Add ChaCha8 and ChaCha20 reduced round variants

- chacha20/CHANGES.md
- chacha20/Cargo.toml
- AVX2 accelerated implementation ([#83])
- ChaCha8 and ChaCha20 reduced round variants ([#84])
- Simplify portable implementation ([#76])
- Make 2018 edition crate; MSRV 1.34+ ([#77])
- Replace `salsa20-core` dependency with `ctr`-derived buffering ([#81])
- `byteorder` dependency ([#80])
[#76]: https://github.com/RustCrypto/stream-ciphers/pull/76
[#77]: https://github.com/RustCrypto/stream-ciphers/pull/77
[#80]: https://github.com/RustCrypto/stream-ciphers/pull/80
[#81]: https://github.com/RustCrypto/stream-ciphers/pull/81
[#83]: https://github.com/RustCrypto/stream-ciphers/pull/83
[#84]: https://github.com/RustCrypto/stream-ciphers/pull/84
> chacha20 v0.3.0

- chacha20/src/block/avx2.rs
- chacha20/src/block/soft.rs
- chacha20/src/block/sse2.rs
- chacha20/src/cipher.rs
Previously when looping through input data, if there was enough data to avoid buffering it was obliterating the plaintext with the keystream rather than XORing it.
This was addressed by adding an `apply_keystream` method to each backend for use in this situation, which avoids the intermediate buffer.
Additionally this commit refactors the AVX2 backend to look more like the SSE2 backend.
> chacha20: Buffering bugfixes and AVX2 backend refactoring

- chacha20/Cargo.toml
- chacha20/README.md
- chacha20/benches/rng.rs
- chacha20/benches/stream_cipher.rs
- chacha20/src/block.rs
- chacha20/src/block/avx2.rs
- chacha20/src/block/soft.rs
- chacha20/src/block/sse2.rs
- chacha20/src/cipher.rs
- chacha20/src/rng.rs
The AVX2 backend was previously computing two ChaCha blocks in parallel, then throwing one away.
This updates the implementation to always compute two blocks in parallel when the AVX2 backend is enabled, resulting in a ~2X speedup.
Unfortunately for `cipher.rs`, originally adapted from the `ctr` crate, I deleted the original parallel computation code, and in lieu of that the implementation diverges from what was originally in `ctr`. See here for a reference:
https://github.com/RustCrypto/stream-ciphers/blob/907e94b/ctr/src/lib.rs#L73
Ideally we can come up with some generic counter management and buffering abstraction in the `ctr` crate which works in all cases.
Benchmark results:
> chacha20: Parallelize AVX2 backend

- chacha20/CHANGES.md
- chacha20/Cargo.toml
- Parallelize AVX2 backend ([#87])
- Benchmark for `ChaCha20Rng` ([#87])
- Fix broken buffering logic ([#86])
[#86]: https://github.com/RustCrypto/stream-ciphers/pull/83
[#87]: https://github.com/RustCrypto/stream-ciphers/pull/84
> chacha20 v0.3.1

- chacha20/src/rng.rs
Previously they weren't marked as being suitable as a CSPRNG.
> chacha20: impl CryptoRng for all ChaCha*Rng types (closes #90)

- chacha20/CHANGES.md
- chacha20/Cargo.toml
- `CryptoRng` marker on all `ChaCha*Rng` types ([#91])
[#91]: https://github.com/RustCrypto/stream-ciphers/pull/91
> chacha20 v0.3.2

- chacha20/src/rng.rs
This is simpler and provides more safety (compiler will ensure correct size) than using a slice-based approach.
> chacha20: use pointer cast to convert RNG buffer type

- chacha20/benches/rng.rs
- chacha20/src/rng.rs
Moves the `&mut` introduced in #96 inside of the `unsafe` block, otherwise the deref acts as a copy, so the copy is mutated rather than the original 😱 
This would have been a vulnerability if released in this state, but was fortunately caught within minutes of the original commit.
Also adds a smoke test to make sure the RNG is generating the expected outputs.
> chacha20: fix array cast

- salsa20/CHANGES.md
- salsa20/Cargo.toml
- salsa20/src/lib.rs
- Replace `salsa20-core` with `ctr`-derived buffering; MSRV 1.34+ ([#94])
[#94]: https://github.com/RustCrypto/stream-ciphers/pull/94
> salsa20 v0.4.0

- .travis.yml
- chacha20/src/block/avx2.rs
- chacha20/src/block/soft.rs
- chacha20/src/block/sse2.rs
- chacha20/src/lib.rs
- chacha20/src/rng.rs
Seems these weren't caught because `-D warnings` was being cleared from the environment.
> chacha20: fix warnings when building with `rng` feature alone

- chacha20/src/block.rs
- chacha20/src/block/avx2.rs
- chacha20/src/block/soft.rs
- chacha20/src/block/sse2.rs
- chacha20/src/cipher.rs
- chacha20/src/legacy.rs
- chacha20/src/lib.rs
- chacha20/src/rng.rs
- chacha20/src/rounds.rs
- chacha20/src/xchacha20.rs
- salsa20/src/cipher.rs
Previously macros were used to generate the ChaCha8, ChaCha12, and ChaCha20 variants of the ChaCha family.
This commit replaces them with a `Rounds` trait, making the `Cipher` type generic over `Rounds`, and replacing the `ChaCha8`, `ChaCha12`, and `ChaCha20` wrappers with type aliases.
In addition to everything else, this makes the number of rounds type safe in that they can only be `R8`, `R12`, or `R20`, eliminating runtime checks around the number of rounds, and also ensuring the number is a constant value known at compile time, which should improve optimizations.
The random number generator types are still generated by macros, unfortunately, but these can be fixed up in a different pass.
> chacha20: replace macros with Rounds trait + generics

- chacha20/src/block/soft.rs
Replaces the previous usage of `mem::zeroed` by hand unrolling the loops that construct the ChaCha20 state array and initializing the state to valid values to begin with.
> chacha20: eliminate unsafe usage in "soft" state init

- chacha20/CHANGES.md
- chacha20/Cargo.toml
- chacha20/src/cipher.rs
- Replace macros with `Rounds` trait + generics ([#100])
- Fix warnings when building with `rng` feature alone ([#99])
[#99]: https://github.com/RustCrypto/stream-ciphers/pull/99
[#100]: https://github.com/RustCrypto/stream-ciphers/pull/100
> chacha20 v0.3.3

- salsa20/CHANGES.md
- salsa20/Cargo.toml
- `hsalsa20` feature ([#103])
[#103]: https://github.com/RustCrypto/stream-ciphers/pull/103
> salsa20 v0.4.1

- chacha20/Cargo.toml
- `zeroize` was accidentally linking against `alloc`
- `rand_core` accidentally linked against `std`
> Cargo.toml: avoid accidental `alloc` and `std` linking

- chacha20/CHANGES.md
- chacha20/Cargo.toml
- Avoid accidental `alloc` and `std` linking ([#105])
[#105]: https://github.com/RustCrypto/stream-ciphers/pull/105
> chacha20 v0.3.4

- .github/workflows/chacha20.yml
- chacha20/README.md
- chacha20/src/block.rs
This crate has a lot of dependencies by way of Criterion. Caching them should help the build performance.
> .github: cache ChaCha20 test artifacts

- Cargo.lock
- Cargo.toml
- ctr/Cargo.toml
- ctr/benches/aes128.rs
- ctr/src/lib.rs
- ctr/tests/mod.rs
Upgrades to Rust 2018 edition and the (now 2018 edition) `stream-cipher` v0.4.0-pre crate.
> ctr: 2018 edition and `stream-cipher` crate upgrade

- Cargo.lock
- Cargo.toml
- cfb-mode/Cargo.toml
- cfb-mode/benches/cfb-mode.rs
- cfb-mode/src/lib.rs
- cfb-mode/tests/mod.rs
Upgrades to Rust 2018 edition and the (now 2018 edition) `stream-cipher` v0.4.0-pre crate.
> cfb-mode: 2018 edition and `stream-cipher` crate upgrade

- Cargo.lock
- cfb8/Cargo.toml
- cfb8/benches/cfb8.rs
- cfb8/src/lib.rs
- cfb8/tests/mod.rs
Upgrades to Rust 2018 edition and the (now 2018 edition) `stream-cipher` v0.4.0-pre crate.
> cfb8: 2018 edition and `stream-cipher` crate upgrade

- Cargo.lock
- chacha20/Cargo.toml
- chacha20/src/cipher.rs
Upgrades to the `stream-cipher` v0.4.0-pre crate.
> chacha20: `stream-cipher` crate upgrade

- Cargo.lock
- ctr/src/lib.rs
- ofb/Cargo.toml
- ofb/benches/cfb-mode.rs
- ofb/src/lib.rs
- ofb/tests/mod.rs
Upgrades to Rust 2018 edition and the (now 2018 edition)\ `stream-cipher` v0.4.0-pre crate.
> ofb: 2018 edition and `stream-cipher` crate upgrade

- Cargo.lock
- salsa20/Cargo.toml
- salsa20/benches/salsa20.rs
- salsa20/src/lib.rs
- salsa20/tests/lib.rs
Upgrades to Rust 2018 edition idioms and the (now 2018 edition) `stream-cipher` v0.4.0-pre crate.
> salsa20: 2018 edition idioms and `stream-cipher` crate upgrade

- Cargo.lock
- aes-ctr/Cargo.toml
- cfb-mode/Cargo.toml
- cfb8/Cargo.toml
- chacha20/Cargo.toml
- ctr/Cargo.toml
- hc-256/Cargo.toml
- ofb/Cargo.toml
- salsa20/Cargo.toml
...to reflect the breaking `stream-cipher` crate update
> Bump all versions to `*-pre`

- Cargo.lock
- salsa20/src/block.rs
- salsa20/src/cipher.rs
- salsa20/src/lib.rs
- salsa20/src/rounds.rs
This adds a generic parameter to `Cipher` and `Block` ala the `chacha20` crate which makes them generic over a number of rounds (using a sealed `Rounds` trait which is explicitly impl'd for `R8`, `R12`, and `R20`).
This is used to provide `Salsa8`, `Salsa12`, and `Salsa20` variants.
The main impetus for this is using `Salsa8` to implement `scrypt`. We could potentially replace the vendored implementation here:
<https://github.com/RustCrypto/password-hashing/blob/master/scrypt/src/romix.rs>
> salsa20: add Salsa8 and Salsa12

- Cargo.lock
> Cargo.lock: bump `stream-cipher` crate

- chacha20/README.md
https://research.nccgroup.com/2020/02/26/public-report-rustcrypto-aes-gcm-and-chacha20poly1305-implementation-review/
> chacha20: add notes about NCC audit

- aes-ctr/README.md
- cfb-mode/README.md
- cfb8/README.md
- ctr/README.md
- hc-256/README.md
- ofb/README.md
- salsa20/README.md
Spelling error: "integerity" -> "integrity"
> README.md(s): fix typo

- Cargo.lock
- Cargo.toml
- aes-ctr/Cargo.toml
- cfb-mode/Cargo.toml
- cfb8/Cargo.toml
- chacha20/Cargo.toml
- ctr/Cargo.toml
- hc-256/Cargo.toml
- ofb/Cargo.toml
- salsa20/Cargo.toml
Updates the following dependencies to use crates.io releases:
- `aes` v0.4.0
- `aes-soft` v0.4.0
- `aesni` v0.7.0
- `block-cipher` v0.7.0
- `stream-cipher` v0.4.0
> Use release versions of crate dependencies

- Cargo.lock
- chacha20/CHANGELOG.md
- chacha20/Cargo.toml
- Upgrade to the `stream-cipher` v0.4 crate ([#121], [#138])
[#138]: https://github.com/RustCrypto/stream-ciphers/pull/138
[#121]: https://github.com/RustCrypto/stream-ciphers/pull/121
> chacha20 v0.4.0

- Cargo.lock
- aes-ctr/Cargo.toml
- ctr/CHANGELOG.md
- ctr/Cargo.toml
- Upgrade to the `stream-cipher` v0.4 crate ([#116], [#138])
- Upgrade to Rust 2018 edition ([#116])
[#138]: https://github.com/RustCrypto/stream-ciphers/pull/138
[#116]: https://github.com/RustCrypto/stream-ciphers/pull/121
> ctr v0.4.0

- .github/workflows/chacha20.yml
Without this it appears to run `cargo test --release` three times in a row.
This changes it to label the steps which test each of the various backends (portable, SSE2, AVX2).
> .github: label chacha20 test steps

- Cargo.lock
- chacha20/CHANGELOG.md
- chacha20/Cargo.toml
- Links in documentation ([#142])
[#142]: https://github.com/RustCrypto/stream-ciphers/pull/142
> chacha20 v0.4.1

- Cargo.lock
- salsa20/CHANGELOG.md
- salsa20/Cargo.toml
- `Salsa8` and `Salsa12` variants ([#133])
- Upgrade to the `stream-cipher` v0.4 crate ([#125], [#138])
[#138]: https://github.com/RustCrypto/stream-ciphers/pull/138
[#133]: https://github.com/RustCrypto/stream-ciphers/pull/133
[#125]: https://github.com/RustCrypto/stream-ciphers/pull/125
> salsa20 v0.5.0

- Cargo.lock
- aes-ctr/CHANGELOG.md
- aes-ctr/Cargo.toml
- cfb-mode/CHANGELOG.md
- cfb-mode/Cargo.toml
- cfb8/CHANGELOG.md
- cfb8/Cargo.toml
- hc-256/CHANGELOG.md
- hc-256/Cargo.toml
- ofb/CHANGELOG.md
- ofb/Cargo.toml
This commit cuts releases of the following crates:
- `aes-ctr` v0.4.0
- `cfb8` v0.4.0
- `cfb-mode` v0.4.0
- `hc-256` v0.1.0
- `ofb` v0.2.0
> Release new crates after 2018 edition / stream-cipher v0.4 upgrade

- Cargo.lock
- Cargo.toml
- salsa20/src/lib.rs
- salsa20/src/xsalsa20.rs
Introduced in this PR:
https://github.com/RustCrypto/traits/pull/188
These eliminate the need to import `GenericArray`! 🎉
> salsa20: use stream_cipher::{Key, Nonce}

- chacha20/src/cipher.rs
- chacha20/src/legacy.rs
- chacha20/src/lib.rs
- chacha20/src/xchacha20.rs
- chacha20/tests/lib.rs
Adds the following type aliases (ala #146):
- `Key`: ChaCha(*) key (including XChaCha20)
- `Nonce`: IETF variant's 96-bit nonce
- `XNonce`: EXtended 96-bit nonce for XChaCha20
- `LegacyNonce`: 64-bit nonce for the legacy "djb" variant
> chacha20: use stream_cipher::{Key, Nonce} type aliases

- chacha20/Cargo.toml
- chacha20/src/legacy.rs
- chacha20/src/lib.rs
- chacha20/src/rng.rs
- chacha20/src/xchacha20.rs
- salsa20/Cargo.toml
- salsa20/src/lib.rs
- salsa20/src/xsalsa20.rs
Adds `doc(cfg(...))` for docs.rs as well as cipher diagrams
> chacha20/salsa20: documentation improvements

- Cargo.lock
- chacha20/CHANGELOG.md
- chacha20/Cargo.toml
- Documentation improvements ([#149])
- `Key`, `Nonce`, `XNonce`, and `LegacyNonce` type aliases ([#147])
[#149]: https://github.com/RustCrypto/stream-ciphers/pull/149
[#147]: https://github.com/RustCrypto/stream-ciphers/pull/147
> chacha20 v0.4.2

- Cargo.lock
- salsa20/CHANGELOG.md
- salsa20/Cargo.toml
- Documentation improvements ([#149])
- `Key`, `Nonce`, and `XNonce` type aliases ([#146])
- Bump `stream-cipher` to v0.4.1 ([#148])
[#149]: https://github.com/RustCrypto/stream-ciphers/pull/149
[#148]: https://github.com/RustCrypto/stream-ciphers/pull/148
[#146]: https://github.com/RustCrypto/stream-ciphers/pull/146
> salsa20 v0.5.1

- salsa20/Cargo.toml
This didn't get properly updated
> salsa20: fix `stream-cipher` version requirement

- Cargo.lock
- salsa20/CHANGELOG.md
- salsa20/Cargo.toml
- Use `Key` and `Nonce` in usage docs ([#155])
- `stream-cipher` version requirement ([#152])
[#155]: https://github.com/RustCrypto/stream-ciphers/pull/155
[#152]: https://github.com/RustCrypto/stream-ciphers/pull/152
> salsa20 v0.5.2

- Cargo.lock
- aes-ctr/CHANGELOG.md
- aes-ctr/Cargo.toml
- aes-ctr/tests/lib.rs
- cfb-mode/CHANGELOG.md
- cfb-mode/Cargo.toml
- cfb8/CHANGELOG.md
- cfb8/Cargo.toml
- chacha20/CHANGELOG.md
- chacha20/Cargo.toml
- chacha20/src/cipher.rs
- chacha20/src/legacy.rs
- chacha20/src/xchacha20.rs
- chacha20/tests/lib.rs
- ctr/CHANGELOG.md
- ctr/Cargo.toml
- ctr/src/lib.rs
- ctr/tests/lib.rs
- hc-256/CHANGELOG.md
- hc-256/Cargo.toml
- hc-256/src/lib.rs
- hc-256/tests/lib.rs
- ofb/CHANGELOG.md
- ofb/Cargo.toml
- salsa20/CHANGELOG.md
- salsa20/Cargo.toml
- salsa20/src/cipher.rs
- salsa20/src/lib.rs
- salsa20/src/xsalsa20.rs
- salsa20/tests/lib.rs
Mostly changes around the new seek trait, plus some improvements of the code for `ctr` and `salsa20`/`chacha20`.
TODO:
@tarcieri 
Can you please check the `salsa20` and `chacha20` changes, especially the latter one? Tests do pass, but I am not 100% confident about changes (and with salsa one mistake almost got through, if not for the single "hello world" test). Note that I've removed the `Option` and instead code now assumes that if buffer position is equal to 0, then the cached buffer is invalid.
> Upgrade to stream-cipher v0.7

- Cargo.lock
- aes-ctr/Cargo.toml
- ctr/Cargo.toml
- ctr/src/ctr128.rs
- ctr/src/ctr32.rs
- ctr/src/lib.rs
Imports and unifies the 32-bit CTR mode implementations previously defined in the `aes-gcm` and `aes-gcm-siv` crates, which implement 32-bit big endian and little endian counter modes respectively.
Additionally impls the `FromBlockCipher` and `SyncStreamCipher` traits for the `Ctr32BE` and `Ctr32LE` wrapper newtypes.
> ctr: vendor/unify Ctr32BE and Ctr32LE types

- Cargo.lock
- aes-ctr/Cargo.toml
- ctr/CHANGELOG.md
- ctr/Cargo.toml
- `Ctr32BE` and `Ctr32LE` ([#170])
[#170]: https://github.com/RustCrypto/stream-ciphers/pull/170
> ctr v0.6.0-pre

- salsa20/src/block.rs
- salsa20/src/lib.rs
- salsa20/src/salsa.rs
- salsa20/src/xsalsa.rs
Unifies the `Salsa`/`SalsaCore` types, as one was previously just a thin wrapper around the other.
This matches the structure of the `chacha20` crate.
> salsa20: internal refactoring

- Cargo.lock
- aes-ctr/CHANGELOG.md
- aes-ctr/Cargo.toml
- cfb-mode/CHANGELOG.md
- cfb-mode/Cargo.toml
- cfb8/CHANGELOG.md
- cfb8/Cargo.toml
- chacha20/CHANGELOG.md
- chacha20/Cargo.toml
- ctr/CHANGELOG.md
- ctr/Cargo.toml
- hc-256/CHANGELOG.md
- hc-256/Cargo.toml
- ofb/CHANGELOG.md
- ofb/Cargo.toml
- salsa20/CHANGELOG.md
- salsa20/Cargo.toml
Releases new versions of all crates in this repository which incorporate the migration to the new `cipher` crate (#177).
> Release new versions

- salsa20/Cargo.toml
- salsa20/src/block.rs
- salsa20/src/lib.rs
- salsa20/src/salsa.rs
Cargo feature to expose `salsa20::Block` as part of the public API.
This can be used by the `scrypt` crate to implement the Salsa20/8 core function, rather than vendoring an implementation. This allows us to work on optimizations in a single place (i.e. this crate).
> salsa20: add `expose-core` feature

- Cargo.lock
- salsa20/CHANGELOG.md
- salsa20/Cargo.toml
- `expose-core` feature ([#180])
[#180]: https://github.com/RustCrypto/stream-ciphers/pull/180
> salsa20 v0.7.1

- README.md
Adds the `rabbit` crate to the toplevel table of stream ciphers
> README.md: add `rabbit` to table

- chacha20/Cargo.toml
It presently refers to the now defunct `stream-cipher` crate
> chacha20/Cargo.toml: update description

- Cargo.lock
- aes-ctr/benches/aes128_ctr.rs
- aes-ctr/benches/aes192_ctr.rs
- aes-ctr/benches/aes256_ctr.rs
- aes-ctr/tests/lib.rs
- cfb-mode/benches/cfb-mode.rs
- cfb-mode/tests/lib.rs
- cfb8/benches/cfb8.rs
- cfb8/tests/lib.rs
- chacha20/benches/chacha12.rs
- chacha20/benches/chacha20.rs
- chacha20/benches/chacha8.rs
- chacha20/tests/lib.rs
- ctr/benches/aes128.rs
- ctr/tests/ctr128/mod.rs
- ofb/benches/cfb-mode.rs
- ofb/tests/lib.rs
- rabbit/benches/rabbit.rs
- salsa20/benches/salsa20.rs
- salsa20/tests/lib.rs
This PR also addresses the deprecation warnings which were introduced
> Bump `cipher` crate to v0.2.5

- salsa20/Cargo.toml
Should be OK as this crate does not use any zeroize alloc functionality.
Stumbled on this when developing embedded firmware, and got the following message during build of the binary:
```
error: no global memory allocator found but one is required; link to std or add `#[global_allocator]` to a static item that implements the GlobalAlloc trait.
```
> salsa20: do not use zeroize default features to prevent alloc inclusion

- Cargo.lock
- salsa20/CHANGELOG.md
- salsa20/Cargo.toml
- `no_std` builds with `zeroize` feature enabled ([#189])
[#189]: https://github.com/RustCrypto/stream-ciphers/pull/189
> salsa20 v0.7.2

- ctr/src/ctr128.rs
Start fixing issue #12. Used the static data from issue to create a test case. Have done some randomized testing with original poc without any issues. At one point included wrap around tests to make sure aes-ctr matched output of openssl, see [comment](https://github.com/RustCrypto/stream-ciphers/pull/75#issuecomment-736608100).
> Ctr128 switch counter u64 to u128

- .github/workflows/chacha20.yml
- Cargo.lock
- chacha20/Cargo.toml
- chacha20/src/backend.rs
- chacha20/src/backend/autodetect.rs
- chacha20/src/backend/avx2.rs
- chacha20/src/backend/soft.rs
- chacha20/src/backend/sse2.rs
- chacha20/src/lib.rs
- chacha20/src/rng.rs
Automatically detects the availability of AVX2 on x86(_64) architectures based on CPUID, and falls back to the SSE2" backend if unavailable.
> chacha20: AVX2 detection

- .github/workflows/chacha20.yml
- chacha20/src/rng.rs
It wasn't necessarily "broken" in that it doesn't really matter what endianness random data comes in, but this at least makes the RNG output consistent on big and little endian platforms.
> chacha20: fix `rng` feature on big endian platforms

- .github/workflows/chacha20.yml
- chacha20/Cargo.toml
- chacha20/src/backend.rs
- chacha20/src/backend/autodetect.rs
- chacha20/src/backend/avx2.rs
- chacha20/src/backend/soft.rs
- chacha20/src/backend/sse2.rs
- chacha20/src/chacha.rs
- chacha20/src/lib.rs
- chacha20/src/rng.rs
- chacha20/src/rounds.rs
- salsa20/src/core.rs
- salsa20/src/lib.rs
- salsa20/src/salsa.rs
- salsa20/src/xsalsa.rs
For consistency, renames the "core" types of both crates to `Core`.
Previously `chacha20` used `State`, which is an odd name for a type which is stateless once initialized.
The `salsa20` used `Block`, which is inconsistent with the name of the `expose-core` feature.
Also adds a semi-hidden (i.e. not visible from https://docs.rs) `expose-core` feature to the `chacha20` crate, similar to the one in the `salsa20` crate (which is used to implement `scrypt`).
> chacha20+salsa20: `Core` types

- Cargo.lock
- ctr/Cargo.toml
Note: the tests are presently failing due to a circular dependency on `aes`, but this release is needed to update `aes` to resolve that problem.
Longer term we should look at ways of eliminating this circular dependency.
> ctr v0.7.0-pre.2

- Cargo.lock
- cfb-mode/Cargo.toml
- cfb-mode/src/lib.rs
- cfb8/Cargo.toml
- ctr/Cargo.toml
- ofb/Cargo.toml
This commit completes working through upgrading the `cipher` crate with circular dependencies between `aes` and `ctr`.
Now that RustCrypto/block-ciphers#217 it's possible to complete the `cipher` crate upgrade started in #205.
All tests are now passing again.
> Enable `aes` dev-dependencies

- Cargo.lock
- cfb-mode/Cargo.toml
- cfb8/Cargo.toml
- chacha20/Cargo.toml
- ctr/Cargo.toml
- hc-256/Cargo.toml
- ofb/Cargo.toml
- rabbit/Cargo.toml
- salsa20/Cargo.toml
Note: this commit disables the (circular) `aes` dependency, so AES-related tests will fail until the `aes` crate can be updated to use the new `ctr` crate.
> Bump `cipher` crate to v0.3.0-pre.4

- Cargo.lock
- cfb-mode/Cargo.toml
- cfb-mode/src/lib.rs
- cfb8/Cargo.toml
- cfb8/src/lib.rs
- ctr/Cargo.toml
- ofb/Cargo.toml
- ofb/src/lib.rs
Completes the `cipher` v0.3.0-pre.4 upgrade started in #208, now that the `aes` crate has been updated as part of this PR:
https://github.com/RustCrypto/block-ciphers/pull/218
> Re-enable `aes` dev-dependencies (again)

- Cargo.lock
- cfb-mode/Cargo.toml
- cfb8/Cargo.toml
- ctr/Cargo.toml
- ofb/Cargo.toml
The `aes` crate is used for several tests, and just got an MSRV breaking change in RustCrypto/block-ciphers#216.
This commit bumps the git dependency to test the crates in this repo with the MSRV changes.
> Bump `aes` crate

- .github/workflows/chacha20.yml
- .github/workflows/workspace.yml
- chacha20/README.md
- chacha20/src/backend/autodetect.rs
- chacha20/src/backend/avx2.rs
- chacha20/src/backend/sse2.rs
Uses the new `core::mem::ManuallyDrop` feature to allow the inner types of unions to be non-Copy.
> chacha20: make autodetect unions non-Copy; MSRV 1.49+

- .github/workflows/chacha20.yml
- chacha20/Cargo.toml
- chacha20/README.md
- chacha20/src/backend.rs
- chacha20/src/chacha.rs
- chacha20/src/lib.rs
- chacha20/src/xchacha.rs
- chacha20/tests/lib.rs
The rationale mostly comes from:
- ["Too Much Crypto" by Jean-Philippe Aumasson](https://eprint.iacr.org/2019/1492.pdf)
- The 7 round design of [Blake3](https://github.com/BLAKE3-team/BLAKE3-specs/blob/master/blake3.pdf)
- The 12 round design of [KangarooTwelve](https://keccak.team/kangarootwelve.html)
- Slide "Status of Keccak & KangarooTwelve cryptanalysis" (page 33) of those [slides](https://keccak.team/files/K12atACNS.pdf)
- The rationale in the [spec](https://keccak.team/files/KangarooTwelve.pdf)
There is probably some more doc to update to reflect the changes made to structures to make them more generic.
Also, it would probably make sense to rename the feature `xchacha20` to `xchacha`.
See also https://github.com/cryptocorrosion/cryptocorrosion/pull/42
> chacha20: add XChaCha8 and XChaCha12

- chacha20/src/chacha.rs
- chacha20/src/lib.rs
- chacha20/tests/lib.rs
It seems that the stream-length-overflow check has been through a few iterations, and at some point along the way it developed troublesome edge-case behavior. This adds 7 unit tests to exercise the behavior, a confusing subset of which (1,2,3,6,7) fail on the current upstream branch. it also adds a simplified stream-length-overflow check and enforces stream-position checking in `try_seek()`. Those changes make all the new tests pass.
Based on a quick glance through the history, I'm not sure when this problem appeared. It doesn't seem easy to exploit unless you're very deliberately extracting more keystream than you should be allowed to, but it definitely needs a fix.
> ChaCha20: Fix stream-length overflow check

- chacha20/src/rng.rs
Removes `derive(Clone)` on `ChaCha*Rng*`.
They date back to the original PR which added RNG support (#63).
Allowing `Clone` on an RNG is problematic because the cloned RNG will have the same internal state, duplicating outputs which can be catastrophic in a cryptographic context.
Instead, the `SeedableRng::from_rng` method can be used to "fork" one RNG from another, seeing a new RNG with an output from another:
https://docs.rs/rand_core/0.6.2/rand_core/trait.SeedableRng.html#method.from_rng
> chacha20: remove `Clone` impls on RNGs

- cfb-mode/Cargo.toml
- cfb8/Cargo.toml
- chacha20/Cargo.toml
- ctr/Cargo.toml
- hc-256/Cargo.toml
- ofb/Cargo.toml
- rabbit/Cargo.toml
- salsa20/Cargo.toml
Due to a cyclical dependency between `aes` and `ctr`, this is expected to fail CI, and can only be fixed by a new `aes` crate release.
> cipher v0.3.0-pre.5

- cfb-mode/Cargo.toml
- cfb8/Cargo.toml
- chacha20/Cargo.toml
- ctr/Cargo.toml
- hc-256/Cargo.toml
- ofb/Cargo.toml
- rabbit/Cargo.toml
- salsa20/Cargo.toml
Due to a cyclical dependency between `aes` and `ctr`, this is expected to fail CI, and can only be fixed by a new `ctr` crate release.
> Bump `cipher` crate dependency to v0.3 release

- ctr/Cargo.toml
Due to a cyclical dependency between `aes` and `ctr`, this is expected to fail CI, and can only be fixed by a new `ctr` crate release.
> ctr v0.7.0-pre.4

- Cargo.lock
- Cargo.toml
- ctr/CHANGELOG.md
- ctr/Cargo.toml
- Generic implementation of CTR ([#195])
- Removed `Ctr32LE` mask bit ([#197])
- Bump `cipher` crate dependency to v0.3 ([#226])
[#195]: https://github.com/RustCrypto/stream-ciphers/pull/195
[#197]: https://github.com/RustCrypto/stream-ciphers/pull/197
[#226]: https://github.com/RustCrypto/stream-ciphers/pull/226
> ctr v0.7.0

- Cargo.lock
- chacha20/CHANGELOG.md
- chacha20/Cargo.toml
- AVX2 detection; MSRV 1.49+ ([#200], [#212])
- `XChaCha8` and `XChaCha12` ([#215])
- Full 64-bit counters ([#217])
- Bump `cipher` crate dependency to v0.3 release ([#226])
- `rng` feature on big endian platforms ([#202])
- Stream-length overflow check ([#216])
- `Clone` impls on RNGs ([#220])
[#200]: https://github.com/RustCrypto/stream-ciphers/pull/200
[#202]: https://github.com/RustCrypto/stream-ciphers/pull/202
[#212]: https://github.com/RustCrypto/stream-ciphers/pull/212
[#215]: https://github.com/RustCrypto/stream-ciphers/pull/215
[#216]: https://github.com/RustCrypto/stream-ciphers/pull/216
[#217]: https://github.com/RustCrypto/stream-ciphers/pull/217
[#220]: https://github.com/RustCrypto/stream-ciphers/pull/220
[#226]: https://github.com/RustCrypto/stream-ciphers/pull/226
> chacha20 v0.7.0

- .github/workflows/chacha20.yml
- chacha20/Cargo.toml
- chacha20/src/lib.rs
- chacha20/src/xchacha.rs
Adds a feature for exposing the `hchacha` function, which is useful for a ChaCha-based `crypto_box`.
> chacha20: add `hchacha` feature

- Cargo.lock
- chacha20/CHANGELOG.md
- chacha20/Cargo.toml
- `hchacha` feature ([#234])
[#234]: https://github.com/RustCrypto/stream-ciphers/pull/234
> chacha20 v0.7.1

- chacha20/tests/lib.rs
While playing with your ChaCha20 implementation I noticed in my tests that I was not able to generate the correct result using the test vectors given in [RFC 8439](https://datatracker.ietf.org/doc/html/rfc8439#section-2.4.2). So I thought I would write the tests to reproduce my problem in this PR. 
However, while writing them I stumbled on this section of the XChaCha tests:
```Rust
// The test vectors omit the first 64-bytes of the keystream
let mut prefix = [0u8; 64];
cipher.apply_keystream(&mut prefix);
```
Adding this to my tests produced the correct results with the test vectors and I am not sure why this is needed. I don't see it mentioned in the RFC. So I wanted to ask why this prefix is needed for the test vectors to produce the correct cipher text? I thought I would contribute the …
> Add RFC 8439 ChaCha20 test vectors test

- chacha20/src/lib.rs
- chacha20/src/xchacha.rs
When looking at the documentation in v0.6 it was possible to see what traits `XChaCha20` implement.
In v0.7 this is no longer possible since `XChaCha` is private and `XChaCha20` is only a type alias.
To fix this, I'm proposing to export `XChaCha`.
> export `XChaCha`

- chacha20/src/backend/avx2.rs
- chacha20/src/backend/sse2.rs
- A bunch of instructions for accessing the 128-bit lanes have been replaced by a union.
- I've implemented a widely-used ChaCha optimisation (that I spotted in `c2-chacha`).
> `chacha20`: Improve AVX2 performance

- .github/workflows/chacha20.yml
- .github/workflows/workspace.yml
- chacha20/README.md
- chacha20/src/backend/autodetect.rs
- chacha20/src/backend/avx2.rs
- chacha20/src/chacha.rs
- chacha20/src/rng.rs
- ctr/src/lib.rs
We switch to a 4-block buffer for the combined SSE2 / AVX2 backend, which allows the AVX2 backend to process them together, while the SSE2 backend continues to process one block at a time.
The AVX2 backend is refactored to enable interleaving the instructions per pair of blocks, for better ILP.
Closes #262.
> `chacha20`: Process 4 blocks at a time in AVX2 backend

- chacha20/src/backend/avx2.rs
The use of `&mut StateWord` everywhere caused a `vmovdqa` to be inserted
after almost every operation, and also caused the diagonalization to use
`vpermilps` instead of seeing the optimisation to `vpshufd`.
The new `State` struct helps to manage the passing-around of owned
`StateWord`s.
> chacha20: Remove mutable borrows from AVX2 backend

- chacha20/Cargo.toml
Now that MSRV is 1.51+, this allows use of `zeroize` 1.4.
> chacha20: lock to `zeroize` <1.5

- chacha20/src/backend/autodetect.rs
i586 targets do not have SSE2 enabled by default.
This commit adds autodetection for SSE2 in addition to the existing autodetection for AVX2, and falls back to a portable implementation if SSE2 is not available.
See discussion here: https://github.com/rust-random/rand/pull/931#issuecomment-907768720
> chacha20: SSE2 autodetection support

- .github/workflows/chacha20.yml
- chacha20/Cargo.toml
- chacha20/src/backend.rs
- chacha20/src/lib.rs
- chacha20/src/xchacha.rs
- chacha20/tests/lib.rs
- salsa20/Cargo.toml
- salsa20/src/lib.rs
- salsa20/src/xsalsa.rs
- salsa20/tests/lib.rs
Removes feature gating of `xchacha20` and `xsalsa20`, making them an always-enabled part of the API.
This cuts down on a growingly excessive number of feature combinations.
> chacha20+salsa20: remove extended-nonce feature gating

- Cargo.lock
- README.md
- chacha20/CHANGELOG.md
- chacha20/Cargo.toml
- chacha20/src/lib.rs
- SSE2 autodetection support ([#270])
- AVX2 performance improvements ([#267], [#267])
- MSRV 1.51+ ([#267])
- Lock to `zeroize` <1.5 ([#269])
- `xchacha` feature: all `XChaCha*` types are now available by-default ([#271])
[#267]: https://github.com/RustCrypto/stream-ciphers/pull/267
[#269]: https://github.com/RustCrypto/stream-ciphers/pull/269
[#270]: https://github.com/RustCrypto/stream-ciphers/pull/270
[#271]: https://github.com/RustCrypto/stream-ciphers/pull/271
> chacha20 v0.8.0

- .github/workflows/chacha20.yml
- chacha20/Cargo.toml
- chacha20/src/backend.rs
- chacha20/src/backend/neon.rs
- chacha20/src/lib.rs
Processes four blocks in parallel. Adapted from the SUPERCOP `dolbeau`
backend (public domain).
Placed behind a new `nightly` feature flag, as aarch64 SIMD intrinsics
are not yet stable.
> chacha20: Add NEON implementation for aarch64

- .github/workflows/rc4.yml
- Cargo.lock
- rc4/Cargo.toml
- rc4/README.md
- rc4/src/lib.rs
- rc4/tests/lib.rs
- Add CI workflow
- Bump version down to 0.0.0 (so we can bump it at publication time)
- Add docs.rs config to Cargo.toml and lib.rs
- Add proper security warning that RC4 is a broken cipher
- Remove superfluous inner `test` module in integration tests
> rc4: various fixups

- chacha20/CHANGELOG.md
This commit contains release notes for the v0.8.2 release of `chacha20`, which backports unpinning `zeroize`, allowing it to build with newer releases of `zeroize`.
The original motivation for pinning it was to preserve MSRV, however this has proven to be extremely problematic in that it prevents what would otherwise be compatible versions of crates from working together.
Users who wish to support lower MSRV should explicitly pin `zeroize` to `<1.5` themselves.
> chacha20: add v0.8.2 release notes

- .github/workflows/benches.yml
- .github/workflows/chacha20.yml
- .github/workflows/hc-256.yml
- .github/workflows/rabbit.yml
- .github/workflows/rc4.yml
- .github/workflows/salsa20.yml
- .github/workflows/workspace.yml
Updates the `actions/checkout` action used in the GitHub Actions workflows to its newest major version.
For a list of changes in [actions/checkout](https://github.com/actions/checkout) see [the changelog](https://github.com/actions/checkout/blob/main/CHANGELOG.md).
As far as I can tell this should all be backwards compatible, so I do not expect any breakage.
> Update actions/checkout in GitHub Actions to v3

- .github/workflows/chacha20.yml
- chacha20/Cargo.toml
- chacha20/README.md
- chacha20/src/backends.rs
- chacha20/src/backends/neon.rs
- chacha20/src/lib.rs
I ported the NEON implementation of ChaCha from Crypto++ (public domain) to Rust with aarch64 intrinsics for a significant performance boost.
Observed performance changes on an Apple M1 Air:
```
name                   chacha-soft ns/iter  chacha-neon ns/iter  diff ns/iter   diff %  speedup
chacha12_bench1_16b    34 (470 MB/s)        28 (571 MB/s)                  -6  -17.65%   x 1.21
chacha12_bench2_256b   477 (536 MB/s)       132 (1939 MB/s)              -345  -72.33%   x 3.61
chacha12_bench3_1kib   1,897 (539 MB/s)     503 (2035 MB/s)            -1,394  -73.48%   x 3.77
chacha12_bench4_16kib  30,811 (531 MB/s)    7,914 (2070 MB/s)         -22,897  -74.31%   x 3.89
chacha20_bench1_16b    51 (313 MB/s)        47 (340 MB/s)                  -4   -7.84%   x 1.09
chacha20_bench2_256b   777 …
```
> chacha20: Add full NEON backend.

- .github/workflows/benches.yml
- .github/workflows/chacha20.yml
- .github/workflows/hc-256.yml
- .github/workflows/rabbit.yml
- .github/workflows/rc4.yml
- .github/workflows/salsa20.yml
- .github/workflows/workspace.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/RustCrypto/stream-ciphers/actions/runs/3596661836:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, actions-rs/cargo@v1
To get rid of some of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain), and the occurrences of `actions-rs/cargo` are replaced by direct …
> Replace unmaintained actions-rs/* actions in CI workflows

- .github/workflows/chacha20.yml
- chacha20/src/backends.rs
- chacha20/src/backends/neon.rs
- chacha20/src/lib.rs
Adds an attribute consistent with the other target-specific cfg attributes for enabling the NEON backend.
This unblocks releasing NEON support as a feature.
> chacha20: add `chacha20_force_neon` cfg attribute

- Cargo.lock
- chacha20/CHANGELOG.md
- chacha20/Cargo.toml
- chacha20/LICENSE-MIT
- chacha20/src/lib.rs
- NEON support via `chacha20_force_neon` cfg attribute ([#310], [#317])
[#310]: https://github.com/RustCrypto/stream-ciphers/pull/310
[#317]: https://github.com/RustCrypto/stream-ciphers/pull/317
> chacha20 v0.9.1

- hc-256/src/lib.rs
Fixing a small bug in the HC-256 stream cipher to use **ptable** instead of **qtable** for the **h2** function. The code properly decrypts up to 0x1000 bytes, but it fails to decrypt data that comes afterward due to this bug.
Data encrypted by the original code can still be fully decrypted despite its length, but will fail to be decrypted by other HC-256 libraries.
> hc-256: use `ptable` instead of `qtable` in `h2` function

- .github/workflows/chacha20.yml
- .github/workflows/hc-256.yml
- .github/workflows/rabbit.yml
- .github/workflows/rc4.yml
- .github/workflows/salsa20.yml
- Cargo.lock
- Cargo.toml
- README.md
- benches/Cargo.toml
- chacha20/Cargo.toml
- chacha20/README.md
- chacha20/src/legacy.rs
- chacha20/src/lib.rs
- chacha20/src/xchacha.rs
- hc-256/Cargo.toml
- hc-256/README.md
- hc-256/src/lib.rs
- rabbit/Cargo.toml
- rabbit/README.md
- rabbit/src/lib.rs
- rc4/Cargo.toml
- rc4/README.md
- rc4/src/lib.rs
- rc4/tests/lib.rs
- salsa20/Cargo.toml
- salsa20/README.md
- salsa20/src/lib.rs
- salsa20/src/xsalsa.rs
This also bumps all of the crate versions to prereleases to denote the breaking change, however they will not have associated releases.
The main change in this prerelease of `cipher` is a migration from `generic-array` to `hybrid-array`.
> Bump `cipher` to v0.5.0-pre.1; MSRV 1.65

- Cargo.lock
- salsa20/Cargo.toml
- salsa20/src/backends.rs
- salsa20/src/backends/soft.rs
- salsa20/src/backends/sse2.rs
- salsa20/src/lib.rs
- salsa20/src/xsalsa.rs
- salsa20/tests/mod.rs
Here i re-added the SSE2 with the caveat of variants. 
- Reverts https://github.com/RustCrypto/stream-ciphers/pull/346 - https://github.com/RustCrypto/stream-ciphers/commit/be4cdb3c965db975e12f568a0c76df3cc4dfefa4
- Add regression tests created in https://github.com/RustCrypto/stream-ciphers/pull/346 - https://github.com/RustCrypto/stream-ciphers/commit/f0781db2ab566d9fad9e11bb8f4b3c7df969e843
- Add the soft fallback for non salsa20/20 variants - https://github.com/RustCrypto/stream-ciphers/commit/3716c623121589669eba101c3be28940fef70504
- Add note about the change - https://github.com/RustCrypto/stream-ciphers/commit/8233bdac709f61e9921fc912241d1d7db4350eaf
> Re-add SSE2 with soft fallback for non salsa20/20 variants

- chacha20/src/backends/soft.rs
- chacha20/src/lib.rs
- chacha20/src/xchacha.rs
The `quarter_round` function is duplicated inside xchacha. We can just use the soft backend version, which is the same code.
https://github.com/RustCrypto/stream-ciphers/pull/348#pullrequestreview-1958048341
> chacha20: unify `quarter_round` in soft backend and xchacha

- .github/workflows/workspace.yml
- chacha20/src/lib.rs
- chacha20/src/rng.rs
Fixes new Clippy warnings and silences the new `unexpected_cfgs` Nightly lint. Additionally, bumps Clippy version used in CI to 1.78.
> chacha20: fix warnings

- chacha20/src/xchacha.rs
> Update URL to match redirect in xchacha.rs

- .github/workflows/chacha20.yml
- chacha20/src/backends.rs
- chacha20/src/lib.rs
- chacha20/src/rng.rs
Enables this functionality by default on `aarch64` targets, all of which have NEON by definition.
The reason it was previously gated like this was because it required what was previously nightly-only functionality, however such functionality has since been stabilized.
> chacha20: remove `chacha20_force_neon` cfg attribute

- Cargo.lock
- chacha20/Cargo.toml
- salsa20/Cargo.toml
- salsa20/src/lib.rs
Cuts the following prereleases:
- `chacha20` v0.10.0-pre.1
- `salsa20` v0.11.0-pre.1
> chacha20+salsa20: cut pre.1 prereleases

- Cargo.lock
- chacha20/Cargo.toml
- chacha20/src/backends/avx2.rs
- chacha20/src/backends/neon.rs
- chacha20/src/backends/soft.rs
- chacha20/src/backends/sse2.rs
- chacha20/src/lib.rs
- chacha20/src/xchacha.rs
- hc-256/Cargo.toml
- hc-256/src/lib.rs
- rabbit/Cargo.toml
- rabbit/src/lib.rs
- rc4/Cargo.toml
- rc4/src/lib.rs
- salsa20/Cargo.toml
- salsa20/src/backends/soft.rs
- salsa20/src/backends/sse2.rs
- salsa20/src/lib.rs
- salsa20/src/xsalsa.rs
> build(deps): bump cipher from 0.5.0-pre.6 to 0.5.0-pre.7

- Cargo.lock
- chacha20/Cargo.toml
- chacha20/src/rng.rs
`rand_core` reworked its error management and now return Infallible error.
> build(deps): bump rand_core from 0.9.0-alpha.1 to 0.9.0-alpha.2

- Cargo.lock
- chacha20/Cargo.toml
- salsa20/Cargo.toml
Cuts the following prereleases:
- `chacha20` v0.10.0-pre.2
- `salsa20` v0.11.0-pre.2
> chacha20+salsa20: cut pre.2 prereleases

- chacha20/Cargo.toml
Closes https://github.com/RustCrypto/AEADs/issues/643
> chacha20: disable default features for zeroize

- chacha20/README.md
- chacha20/src/backends/sse2.rs
- chacha20/src/rng.rs
By changing the output buffer for the SSE2 backend to 4 blocks, I was able to improve the performance by +83% more throughput for `cipher` and +90% more throughput for the `rng`
Closes #379
> Improved SSE2 throughput by up to +90%

- Cargo.lock
- chacha20/Cargo.toml
Note: this release supports `rand_core` v0.9
> chacha20 v0.10.0-pre.3

- chacha20/src/rng.rs
Just checking to see if GitHub actions fails here
Fixes #388
> chacha20: rng - stream ID endianness

- chacha20/src/backends/neon.rs
- chacha20/src/rng.rs
fixes #381 
seeing if the test fails on github actions; it fails on my Mac with `cargo test --features rng` and passes with `RUSTFLAGS="--cfg chacha20_force_soft"`
Once this is fixed, there *should be* no more bugs with the RNG. I might add one more endian test for peace of mind though.
> chacha20: rng - Fixing NEON Backend

- chacha20/src/rng.rs
Got rid of some magic numbers, improved readability, and removed duplicate code. Also marked these functions as `#[inline]`, since they get compiled into a few moves (I've checked that this is the case for all three of them).
Any idea when `chacha20` will be ready for a full 0.10.0 release?
> chacha20: Improve quality of `StreamId` `From` impls and some related documentation

- chacha20/Cargo.toml
- hc-256/Cargo.toml
- rabbit/Cargo.toml
- rc4/Cargo.toml
- salsa20/Cargo.toml
See https://github.com/RustCrypto/meta/issues/22
> Use the standard order of the `[package]` section fields

- chacha20/Cargo.toml
- chacha20/src/rng.rs
@nstilt1 what was the impetus for naming this `serde1` in the first place?
I'm also a little worried these impls exist at all. What's the use case for serializing RNG state? It seems like a footgun that could lead to keystream reuse.
> chacha20: rename `serde1` feature to `serde`
