- chacha20/src/lib.rs
This fixes all but one remaining clippy warning which I'll open a separate PR for.
> chacha20: Fix clippy warnings

- ctr/src/lib.rs
This PR is an alternative to #32 to fix the final clippy warning.
The previous pointer casting here was not clippy-friendly:
```
error: casting from `*const stream_cipher::generic_array::GenericArray<u8, stream_cipher::generic_array::typenum::UInt<stream_cipher::generic_array::typenum::UInt<stream_cipher::generic_array::typenum::UInt<stream_cipher::generic_array::typenum::UInt<stream_cipher::generic_array::typenum::UInt<stream_cipher::generic_array::typenum::UTerm, stream_cipher::generic_array::typenum::B1>, stream_cipher::generic_array::typenum::B0>, stream_cipher::generic_array::typenum::B0>, stream_cipher::generic_array::typenum::B0>, stream_cipher::generic_array::typenum::B0>>` to a more-strictly-aligned pointer (`*const [u64; 2]`)
--> ctr/src/lib.rs:90:17
|
90 |                 nonce …
```
> ctr: Use clippy-friendly unsafe endianness conversion

- chacha20/CHANGES.md
- chacha20/Cargo.toml
- salsa20-core/CHANGES.md
- Add `MAX_BLOCKS` and `BLOCK_SIZE` constants (#47)
> chacha20 v0.2.1

- chacha20/README.md
- salsa20/CHANGES.md
- salsa20/Cargo.toml
- salsa20/README.md
- XSalsa20 ([#54])
[#54]: https://github.com/RustCrypto/stream-ciphers/pull/44
> salsa20 v0.3.0

- Cargo.toml
- hc-256/Cargo.toml
- hc-256/LICENSE-APACHE
- hc-256/LICENSE-MIT
- hc-256/src/lib.rs
- hc-256/tests/mod.rs
This PR adds an implementation of the HC-256 cipher.  HC-256 was introduced in 2004 by Hongjun Wu, and is one of the finalists in the eSTREAM cipher competition.
> Add HC-256 cipher implementation

- README.md
- hc-256/CHANGES.md
- hc-256/Cargo.toml
> hc-256 v0.0.1

- chacha20/CHANGES.md
- chacha20/Cargo.toml
- Ensure block counter < MAX_BLOCKS ([#68])
[#68]: https://github.com/RustCrypto/stream-ciphers/pull/68
> chacha20 v0.2.3

- chacha20/src/block/sse2.rs
Splits out `key_setup` and `iv_setup` methods, removing redundant initialization.
> chacha20: minor SSE2 backend refactoring

- chacha20/CHANGES.md
> chacha20: Fix links in CHANGES.md

- aes-ctr/src/lib.rs
- cfb-mode/src/lib.rs
- cfb8/src/lib.rs
- ctr/src/lib.rs
- hc-256/src/lib.rs
- ofb/src/lib.rs
- salsa20/src/block.rs
- salsa20/src/lib.rs
Adds the RustCrypto logo for all crates
Lints for:
- 2018 idioms
- Unsafe code (where possible)
> Add standard set of attributes to all crates

- aes-ctr/Cargo.toml
- cfb-mode/Cargo.toml
- cfb8/Cargo.toml
- chacha20/Cargo.toml
- ctr/Cargo.toml
- hc-256/Cargo.toml
- ofb/Cargo.toml
- salsa20/Cargo.toml
https://crates.io has dropped support for them
> Cargo.toml(s): remove [badge]s

- Cargo.lock
- ctr/Cargo.toml
- ctr/src/lib.rs
- ctr/tests/lib.rs
Impls the new `FromBlockCipher` trait introduced in:
https://github.com/RustCrypto/traits/pull/164
> ctr: impl FromBlockCipher

- chacha20/src/cipher.rs
> chacha20: fix documentation typo

- chacha20/src/lib.rs
- salsa20/src/lib.rs
...in lieu of using `GenericArray` directly, which is cumbersome.
> chacha20/salsa20: use `Key` and `Nonce` in usage docs

- Cargo.lock
- chacha20/CHANGELOG.md
- chacha20/Cargo.toml
- Documentation improvements ([#153], [#154], [#155])
[#153]: https://github.com/RustCrypto/stream-ciphers/pull/155
[#154]: https://github.com/RustCrypto/stream-ciphers/pull/155
[#155]: https://github.com/RustCrypto/stream-ciphers/pull/155
> chacha20 v0.4.3

- aes-ctr/README.md
- cfb-mode/README.md
- cfb8/README.md
- chacha20/README.md
- ctr/README.md
- hc-256/README.md
- ofb/README.md
- salsa20/README.md
- Fix broken Unicode
- Link to https://github.com/RustCrypto/meta/blob/master/HAZMAT.md
> README.md(s): update "hazmat" badges

- README.md
- aes-ctr/README.md
- cfb-mode/README.md
- cfb8/README.md
- chacha20/README.md
- ctr/README.md
- hc-256/README.md
- ofb/README.md
- salsa20/README.md
Also some toplevel README.md fixups and associated badge fixups.
> README.md(s): add Zulip badges

- .github/workflows/rabbit.yml
- Cargo.lock
- Cargo.toml
- rabbit/Cargo.toml
- rabbit/LICENSE-APACHE
- rabbit/LICENSE-MIT
- rabbit/README.md
- rabbit/benches/rabbit.rs
- rabbit/src/lib.rs
Closes #171.
This PR adds support of the Rabbit Stream Cipher Algorithm (see [RFC 4503][1]).
[1]: https://tools.ietf.org/html/rfc4503
> Rabbit Stream Cipher

- .github/workflows/hc-256.yml
- .github/workflows/rabbit.yml
- .github/workflows/salsa20.yml
- hc-256/Cargo.toml
- rabbit/Cargo.toml
- salsa20/Cargo.toml
Also test `zeroize` builds in CI
> hc-256/rabbit: avoid pulling in `alloc` feature of `zeroize`

- chacha20/src/backend.rs
- chacha20/src/backend/avx2.rs
- chacha20/src/backend/soft.rs
- chacha20/src/backend/sse2.rs
- chacha20/src/chacha.rs
- chacha20/src/lib.rs
- chacha20/src/rng.rs
- chacha20/src/xchacha.rs
...to `State`, for more consistency with other RustCrypto projects
> chacha20: rename `backend` module and types

- cfb-mode/Cargo.toml
- cfb8/Cargo.toml
- chacha20/Cargo.toml
- ctr/Cargo.toml
- hc-256/Cargo.toml
- ofb/Cargo.toml
- rabbit/Cargo.toml
- salsa20/Cargo.toml
This reverts commit 7786dc4e81b543a507a64ad7c014619c493722d3.
I wasn't able to figure out how to complete this update.
> Revert "cipher v0.3.0-pre.5 (#224)"

- Cargo.lock
- chacha20/Cargo.toml
- chacha20/src/backend/autodetect.rs
> chacha20: use `cpufeatures` v0.1 crate release

- Cargo.lock
- chacha20/CHANGELOG.md
- chacha20/Cargo.toml
- hc-256/CHANGELOG.md
- hc-256/Cargo.toml
- rabbit/CHANGELOG.md
- rabbit/Cargo.toml
- salsa20/CHANGELOG.md
- salsa20/Cargo.toml
> Pin zeroize to v1.3

- Cargo.lock
- rc4/CHANGELOG.md
- rc4/Cargo.toml
- rc4/README.md
- rc4/src/lib.rs
> rc4 v0.1.0

- Cargo.lock
> Update cpufeatures to v0.2.5

- chacha20/src/lib.rs
> Fix some typos

- README.md
- chacha20/README.md
- hc-256/README.md
- rabbit/README.md
- rc4/README.md
- salsa20/README.md
Additionally removes the MSRV section from the root README since we relaxed our MSRV policy.
> Fix build badges
